version: "3.0"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.2
    # NOTE: the default vm.max_map_count maynot be enough to 
    #       run elasticsearch increase it to at least  262144
    # sudo sysctl vm.max_map_count=262144
    # volumes:
    #   - esdata:/usr/share/elasticsearch/data
    networks:
     - logging
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - "9200:9200"
    container_name:
      elasticsearch
      
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.2
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    volumes:
      - ./kibana-cfg:/etc/kibana
    networks:
      - logging
    ports:
      - "5601:5601"
    links:
      - "elasticsearch:elasticsearch"
    container_name:
      kibana
      
  logstash:
    image: docker.elastic.co/logstash/logstash:5.4.2
    # NOTE: logstash isn't updating ES with command, might be an entry script bug
    # command: -f /config-dir/apache.conf --log.level debug --config.debug
    # entrypoint: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ${PWD}/logstash/config/:/config-dir/
      - ${PWD}/logstash/data-dir/:/data-dir/
    entrypoint: logstash -f /config-dir/
    networks:
      - logging
    deploy:
      mode: global
    ports:
      - "4560:4560/udp"
    links:
      - "elasticsearch:elasticsearch"
      - "redis:redis"
    container_name:
      logstash

  filebeat:
    image: willfarrell/filebeat:5
    volumes:
      - ${PWD}/filebeat/filebeat.yml:/etc/filebeat/filebeat.yml
      - ${PWD}/filebeat/data-dir/:/data-dir/
    networks:
      - logging
    links:
      - "redis:redis"
    container_name:
      filebeat

  redis:
    image : redis:3.0
    networks:
      - logging
    container_name:
      redis

  phpredisadmin:
    image: actency/docker-phpredisadmin
    ports:
      - "9900:80"
    environment:
      - REDIS_1_HOST=redis
    networks:
      - logging
    links:
      - "redis:redis"
    container_name:
      phpredisadmin

networks:
  logging:
    driver: bridge

volumes:
  esdata: